# Docker
alias docker-compose="docker compose "
alias d=docker
alias di="docker images"
alias dc="docker compose"
alias dpa="docker ps -a"

# Git
alias g=git

alias ga="git add"
alias gaa="git add --all"

alias gd="git diff"
alias gdc="git diff --cached"
alias gds="git diff --stat"

alias gf="git fetch --all --prune"

#alias gll="git log --pretty="
#alias gls="git log --pretty="

alias gp="git pull"
alias gpu="git push"

alias gs="git status"
alias gss="git status -s"

# Kubernetes
alias k=kubectl

# Tofu
alias tf=tofu
alias tfa="tofu apply"
alias tfd="tofu destroy"
alias tff="tofu fmt -recursive"
alias tfi="tofu init"
alias tfo="tofu output"
alias tfp="tofu plan"
alias tfs="tofu show"
alias tfv="tofu validate"

# Watch
alias watch="watch "
alias w="watch -n 0.3 "
